name: Check PKGBUILDs

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install packages
      run: |
        pacman -Syu --noconfirm
        pacman -S python git libffi --noconfirm --needed

    - name: Install project's namcap fork
      run: |
        git clone https://github.com/angelofallars/namcap.git

    - name: Run namcap
      working-directory: ./namcap
      run: |
        python namcap.py test/grub/PKGBUILD
